"""Create Game Model

Revision ID: d1e5d1fc7afa
Revises: 38204be7f734
Create Date: 2024-11-13 16:21:06.151454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e5d1fc7afa'
down_revision = '38204be7f734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
